### ISSUE TITLE
#today's_hope

### ISSUE THREAD

**Issue by antoqadri** [hajirodeon/wappswandroid#2]
Makin keren aja neh materinya.. semoga berkah ilmunya. makin sehat dan sejahtera pelatihnya.. amin

**Comment by antoqadri** [comment]
![download](https://user-images.githubusercontent.com/35720551/35283298-dba299b6-0092-11e8-9d92-8e3c113f64e2.jpg)

**Comment by hajirodeon** [comment]
mantap...
